### registrar show

POST http://localhost:3003/shows/register/a1a0b5b0-e682-4609-9e62-2754a4f361b2
Content-Type: application/json

{
    "weekDay":"Sábado",
    "startTime":10,
    "endTime":11
}

### todos os shows

GET http://localhost:3003/shows/allshows
Content-Type: application/json

### shows do dia

GET http://localhost:3003/shows/showsByDay/sexta
Content-Type: application/json